language: python
python: 2.7
env:
  - TOXENV=py26-1.4
  - TOXENV=py26-1.5
  - TOXENV=py26-1.6
  - TOXENV=py27-1.4
  - TOXENV=py27-1.5
  - TOXENV=py27-1.6
  - TOXENV=py33-1.5
  - TOXENV=py33-1.6
  - TOXENV=pypy-1.4
  - TOXENV=pypy-1.5
  - TOXENV=pypy-1.6
  - TOXENV=docs
before_install:
  - sudo apt-get -q -y update
  - sudo apt-get -q -y install binutils gdal-bin libproj-dev libgeos-c1
install:
  - pip install tox flake8
before_script:
  - flake8 floppyforms
script:
  - tox -e $TOXENV
notifications:
  irc:
    channels:
      - "irc.freenode.org#django-floppyforms"
    on_success: change
    on_failure: always
